`timescale 1ns/1ps

module tb_export_check;

    reg clk = 0;
    reg rst;
    reg in_sensor, out_sensor, ent, t_allow;
    wire open_door, close_door;
    wire [3:0] occupancy;

    integer errors = 0;

    waiting_room DUT (
        .clk        (clk),
        .rst        (rst),
        .in_sensor  (in_sensor),
        .out_sensor (out_sensor),
        .ent        (ent),
        .t_allow    (t_allow),
        .open_door  (open_door),
        .close_door (close_door),
        .occupancy0 (occupancy[0]),
        .occupancy1 (occupancy[1]),
        .occupancy2 (occupancy[2]),
        .occupancy3 (occupancy[3])
    );

    always #5 clk = ~clk;

    task tick;
        begin
            @(posedge clk);
            #1;
        end
    endtask

    task check_occ(input [3:0] expected, input [127:0] label);
        begin
            if (occupancy !== expected) begin
                $display("FAIL [%0s] time=%0t occupancy=%0d expected=%0d", label, $time, occupancy, expected);
                errors = errors + 1;
            end
        end
    endtask

    task check_bit(input got, input expected, input [127:0] label);
        begin
            if (got !== expected) begin
                $display("FAIL [%0s] time=%0t got=%0b expected=%0b", label, $time, got, expected);
                errors = errors + 1;
            end
        end
    endtask

    task press_ent(input allow, input under_cap);
        begin
            t_allow = allow;
            ent = 1'b1;
            tick;
            ent = 1'b0;
            tick;
        end
    endtask

    task pass_in;
        begin
            in_sensor = 1'b1;
            tick;
            in_sensor = 1'b0;
        end
    endtask

    task pass_out;
        begin
            out_sensor = 1'b1;
            tick;
            out_sensor = 1'b0;
        end
    endtask

    integer i;

    initial begin
        $dumpfile("export_check.vcd");
        $dumpvars(0, tb_export_check);
        rst = 1; ent = 0; in_sensor = 0; out_sensor = 0; t_allow = 1;
        tick; tick;
        rst = 0;
        tick;

        // 1) reset state
        check_occ(4'd0, "reset->occupancy0");
        check_bit(close_door, 1'b1, "reset->close_door");
        check_bit(open_door, 1'b0, "reset->open_door");

        // 2) simple entrance: press Ent, door opens, stays open until IN pulse
        press_ent(1, 1);
        check_bit(open_door, 1'b1, "after ent->open");
        tick; tick; // hold: still open, nobody passed yet
        check_bit(open_door, 1'b1, "still waiting->open held");
        pass_in;
        tick;
        check_bit(open_door, 1'b0, "after in pulse->open closes");
        check_occ(4'd1, "after 1 entry->occupancy1");
        check_bit(close_door, 1'b0, "occupancy1->close_door low");

        // 3) fill the room to capacity (15)
        for (i = 2; i <= 15; i = i + 1) begin
            press_ent(1, 1);
            pass_in;
        end
        tick;
        check_occ(4'd15, "filled to capacity->occupancy15");

        // 4) 16th person should be refused: Ent pressed at count==15 -> no open
        press_ent(1, 1);
        check_bit(open_door, 1'b0, "room full->ent refused");

        // stray IN pulse should NOT be generated by a real system when the
        // door never opened; counter itself would still track a physical
        // pulse if one occurred, but here we simply confirm the door logic
        // blocked the request.

        // 5) someone exits: occupancy 15 -> 14, exit door stays open (no close)
        pass_out;
        tick;
        check_occ(4'd14, "after 1 exit->occupancy14");
        check_bit(close_door, 1'b0, "occupancy14->close_door low");

        // 6) now under capacity again, Ent should be able to open the door
        press_ent(1, 1);
        check_bit(open_door, 1'b1, "under capacity again->ent opens");
        pass_in;
        tick;
        check_occ(4'd15, "back to 15->occupancy15");

        // 7) simultaneous IN and OUT in the same clock pulse -> no net change
        in_sensor = 1'b1; out_sensor = 1'b1;
        tick;
        in_sensor = 1'b0; out_sensor = 1'b0;
        tick;
        check_occ(4'd15, "simultaneous in&out->occupancy unchanged");

        // 8) drain the room completely
        for (i = 15; i >= 1; i = i - 1) begin
            pass_out;
        end
        tick;
        check_occ(4'd0, "drained->occupancy0");
        check_bit(close_door, 1'b1, "occupancy0->close_door high");

        // 9) T=0 (permitted hour passed) blocks entrance even with room empty
        press_ent(0, 1);
        check_bit(open_door, 1'b0, "t_allow=0->ent refused");

        // 10) T=1 again works
        press_ent(1, 1);
        check_bit(open_door, 1'b1, "t_allow=1->ent opens again");
        pass_in;
        tick;
        check_occ(4'd1, "final sanity->occupancy1");

        // 11) holding Ent down (level, not a fresh pulse) must not re-open
        //     the door or re-trigger admission on every clock tick.
        pass_in; // clears open_door from step 10's remaining state if any
        rst = 1; tick; rst = 0; tick;
        ent = 1'b1;
        tick; // rising edge -> should open (occupancy 0 < 15, t_allow=1)
        check_bit(open_door, 1'b1, "level ent->opens once on edge");
        pass_in; // person passes, occupancy->1, open should clear even though ent still held
        tick;
        check_bit(open_door, 1'b0, "ent held down->open still clears on IN");
        ent = 1'b0;
        tick;

        if (errors == 0)
            $display("ALL TESTS PASSED");
        else
            $display("%0d TEST(S) FAILED", errors);

        $finish;
    end

endmodule
