/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "comparator_1bit.v:3.1-13.10" *)
module comparator_1bit(a, b, gt, eq, lt);
  (* src = "comparator_1bit.v:4.17-4.18" *)
  input a;
  wire a;
  (* src = "comparator_1bit.v:5.17-5.18" *)
  input b;
  wire b;
  (* src = "comparator_1bit.v:7.17-7.19" *)
  output eq;
  wire eq;
  (* src = "comparator_1bit.v:6.17-6.19" *)
  output gt;
  wire gt;
  (* src = "comparator_1bit.v:8.17-8.19" *)
  output lt;
  wire lt;
  assign eq = ~(a ^ b);
  assign gt = a & ~(b);
  assign lt = b & ~(a);
endmodule

(* top =  1  *)
(* src = "comparator_4bit.v:3.1-28.10" *)
module comparator_4bit(a, b, gt, eq, lt);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "comparator_4bit.v:4.23-4.24" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "comparator_4bit.v:5.23-5.24" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "comparator_4bit.v:11.16-11.22" *)
  wire [3:0] bit_eq;
  (* src = "comparator_4bit.v:10.16-10.22" *)
  wire [3:0] bit_gt;
  (* src = "comparator_4bit.v:12.16-12.22" *)
  wire [3:0] bit_lt;
  (* src = "comparator_4bit.v:7.23-7.25" *)
  output eq;
  wire eq;
  (* src = "comparator_4bit.v:6.23-6.25" *)
  output gt;
  wire gt;
  (* src = "comparator_4bit.v:8.23-8.25" *)
  output lt;
  wire lt;
  assign _00_ = bit_eq[1] & bit_eq[0];
  assign _01_ = ~(bit_eq[3] & bit_eq[2]);
  assign eq = _00_ & ~(_01_);
  assign _02_ = bit_gt[2] & bit_eq[3];
  assign _03_ = _02_ | bit_gt[3];
  assign _04_ = bit_gt[1] & ~(_01_);
  assign _05_ = _04_ | _03_;
  assign _06_ = _01_ | ~(bit_eq[1]);
  assign _07_ = bit_gt[0] & ~(_06_);
  assign gt = _07_ | _05_;
  assign _08_ = bit_lt[2] & bit_eq[3];
  assign _09_ = _08_ | bit_lt[3];
  assign _10_ = bit_lt[1] & ~(_01_);
  assign _11_ = _10_ | _09_;
  assign _12_ = bit_lt[0] & ~(_06_);
  assign lt = _12_ | _11_;
  (* module_not_derived = 32'd1 *)
  (* src = "comparator_4bit.v:17.21-17.68" *)
  comparator_1bit c0 (
    .a(a[0]),
    .b(b[0]),
    .eq(bit_eq[0]),
    .gt(bit_gt[0]),
    .lt(bit_lt[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "comparator_4bit.v:16.21-16.68" *)
  comparator_1bit c1 (
    .a(a[1]),
    .b(b[1]),
    .eq(bit_eq[1]),
    .gt(bit_gt[1]),
    .lt(bit_lt[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "comparator_4bit.v:15.21-15.68" *)
  comparator_1bit c2 (
    .a(a[2]),
    .b(b[2]),
    .eq(bit_eq[2]),
    .gt(bit_gt[2]),
    .lt(bit_lt[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "comparator_4bit.v:14.21-14.68" *)
  comparator_1bit c3 (
    .a(a[3]),
    .b(b[3]),
    .eq(bit_eq[3]),
    .gt(bit_gt[3]),
    .lt(bit_lt[3])
  );
endmodule
